 #(以下为测试用的配置, 生产环境的密码密钥类数据请勿上传到公开代码仓库)
server:
  mode: debug  # 开发环境用debug，生产环境用release
  port: "8080"

db:
  type: "mysql"  # 数据库类型：postgres 或 mysql
  # 可以继续使用 DSN 方式（向后兼容）
  #dsn: "host=localhost user=root password=123456 dbname=auth_service port=3306 sslmode=disable"
  # 或者使用新的分离配置方式（如果不使用 dsn，请注释掉上面的 dsn 行，启用下面的配置）
  # host: "localhost"
  # port: "5432"
  # user: "postgres"
  # password: "your_db_password"
  # dbname: "auth"
  # sslmode: "disable"  # PostgreSQL 专用
  
  # MySQL 配置示例（将 type 改为 "mysql" 并启用下面的配置）
  host: "39.106.249.152"
  port: "3306"
  user: "root"
  password: "123456"
  dbname: "auth_service"
  charset: "utf8mb4"
  parsetime: true
  loc: "Local"

redis:
  host: "39.106.249.152"
  port: "6379"
  password: "123456"
  db: 0
  prefix: "auth_service:"

jwt:
  secret: "auth_service_jwt_secret"  # 生产环境需更换为强密钥

log:
  level: info

# OAuth2 配置
oauth2:
  github:
    app_name: "ProdOAuthApp"  # OAuth App 名称
    client_id: "Ov23lioGTbgqWyZ6YRYU"          # 从 GitHub OAuth App 获取
    client_secret: "57d59d856c000d8fcc862458c95f412252fc05a8"   # 从 GitHub OAuth App 获取
    redirect_url: "http://39.106.249.152:8080/auth/oauth2/github/callback"

# 前端页面配置
ui:
  base_url: "http://39.106.249.152"           # 前端应用基础URL
  login_success_path: "/success"         # 登录成功页面路径
  login_error_path: "/error"             # 登录失败页面路径

# hCaptcha 配置
hcaptcha:
  enabled: true
  secret_key: "ES_d4d2c1fb309a4587b3c380102665cb5c"
  site_key: "1b8ef492-12ba-4f48-9508-8b4646748548"