#(生产环境配置模板，请填写实际的生产环境配置信息)
server:
  mode: "release"  # 生产环境使用 release 模式
  port: "8080"

db:
  type: "mysql"  # 数据库类型：postgres 或 mysql
  host: ""
  port: "3306"
  user: ""
  password: ""
  dbname: ""
  charset: "utf8mb4"
  parsetime: true
  loc: "Local"

redis:
  host: ""
  port: "6379"
  password: ""
  db: 0
  prefix: "auth_service:"

jwt:
  secret: ""  # 请使用至少32位的强密钥

log:
  level: "info"

# OAuth2 配置
oauth2:
  github:
    app_name: ""  # OAuth App 名称
    client_id: ""          # 从 GitHub OAuth App 获取
    client_secret: ""   # 从 GitHub OAuth App 获取
    redirect_url: ""  # 生产环境回调URL

# 前端页面配置
ui:
  base_url: ""           # 前端应用基础URL
  login_success_path: "/success"         # 登录成功页面路径
  login_error_path: "/error"             # 登录失败页面路径

# hCaptcha 配置
hcaptcha:
  enabled: true
  secret_key: ""
  site_key: ""